const achievements = [
  {
    name: "Chat Rookie",
    description: "Send your first chat message",
    badgeImageUrl: "/public/badges/chat_rookie.png",
    isTaken: true,
    condition: "Send at least one chat message",
  },
  {
    name: "Active Chatter",
    description: "Send 10 chat messages",
    badgeImageUrl: "/public/badges/active_chatter.png",
    isTaken: true,
    condition: "Send a total of 10 chat messages",
  },
  {
    name: "Chat Addict",
    description: "Send 100 chat messages",
    badgeImageUrl: "/public/badges/chat_addict.png",
    isTaken: false,
    condition: "Send a total of 100 chat messages",
  },
  {
    name: "Chatterbox",
    description: "Send 500 chat messages",
    badgeImageUrl: "/public/badges/chatterbox.png",
    isTaken: false,
    condition: "Send a total of 500 chat messages",
  },
  {
    name: "Chat Master",
    description: "Send 1000 chat messages",
    badgeImageUrl: "/public/badges/chat_master.png",
    isTaken: false,
    condition: "Send a total of 1000 chat messages",
  },
  {
    name: "Engagement Pro",
    description: "Engage in a long chat session",
    badgeImageUrl: "/public/badges/engagement_pro.png",
    isTaken: false,
    condition: "Engage in a chat session lasting at least 1 hour",
  },
  {
    name: "Chat Explorer",
    description: "Discover all chat features",
    badgeImageUrl: "/public/badges/chat_explorer.png",
    isTaken: false,
    condition: "Use all available chat features",
  },
  {
    name: "Conversation Starter",
    description: "Initiate a conversation topic",
    badgeImageUrl: "/public/badges/conversation_starter.png",
    isTaken: true,
    condition: "Start a conversation topic in the chat",
  },
  {
    name: "Voice Novice",
    description: "Use voice input for the first time",
    badgeImageUrl: "/public/badges/voice_novice.png",
    isTaken: true,
    condition: "Use voice input at least once",
  },
  {
    name: "Multilingual Speaker",
    description: "Converse with the chatbot using multiple languages",
    badgeImageUrl: "/public/badges/multilingual_speaker.png",
    isTaken: false,
    condition:
      "Engage in a conversation with the chatbot using at least 3 different languages",
  },
  {
    name: "Voice Master",
    description: "Use voice input in all available chat models",
    badgeImageUrl: "/public/badges/voice_master.png",
    isTaken: false,
    condition: "Successfully use voice input with all available chat models",
  },
  {
    name: "Model Maestro",
    description: "Master all chat model types",
    badgeImageUrl: "/public/badges/model_maestro.png",
    isTaken: true,
    condition: "Achieve proficiency in using all available chat model types",
  },
];
